version: '3'
services:
  laser-keyence:
    build: .
    working_dir: /home/laser-keyence
    volumes:
      - .:/home/laser-keyence
    command: bash -c "
      colcon build &&
      . install/setup.bash &&
      ros2 run cloud_points_publisher laser"